<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>

<!DOCTYPE drinks [
<!ELEMENT drinks (drink+)>
<!ELEMENT drink (ingredients,prep,(comment?),nutrition,rating)>
<!ATTLIST drink title CDATA #REQUIRED>
<!ELEMENT ingredients (ingredient+)>
<!ELEMENT ingredient EMPTY>
<!ATTLIST ingredient name CDATA #REQUIRED amount CDATA #REQUIRED unit CDATA #IMPLIED>
<!ELEMENT prep (step+)>
<!ELEMENT step (#PCDATA)>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT nutrition EMPTY>
<!ATTLIST nutrition protein CDATA #REQUIRED 
                    fiber CDATA #REQUIRED 
                    calories CDATA #IMPLIED
                    fat CDATA #IMPLIED
                    carbohydrates CDATA #IMPLIED>
<!ELEMENT rating (#PCDATA)>
]>

<drinks>
<drink title="Lemon Shots">
       <ingredients>
       <ingredient name="lemon" amount="2"></ingredient>
       <ingredient name="sugar powder" amount="2 table spoons"></ingredient>
       <ingredient name="ice cubes" amount="3"></ingredient>
       <ingredient name="salt" amount="half tea spoon"></ingredient>
       <ingredient name="soda" amount="100" unit="litre"></ingredient>
       </ingredients>
       <prep> 
           <step>put some ice cubed in a glass</step>
           <step>add a pinch of salt</step>
           <step>pour 2 table spoons of lemon juice</step>
           <step>add some powered sugar</step>
           <step>pour 100ml of soda</step>
           <step>shake it well and serve</step>
       </prep>
       <comment>
            make lemon juice before starting with the recipe
       </comment>
       <nutrition calories="29" fat="0.3" carbohydrates="9.3" protein="1.1" fiber="2.8"></nutrition>
       <rating>9 out of 10</rating>
</drink>
<drink title="Apple Milkshake">
       <ingredients>
       <ingredient name="apples" amount="2"></ingredient>
       <ingredient name="milk" amount="1 cup" unit="ml"></ingredient>
       <ingredient name="powered sugar" amount="3 table spoons"></ingredient>
       <ingredient name="ice cubes" amount="2" unit="ml"></ingredient>
       </ingredients>
       <prep> 
           <step>dice apples</step>
           <step>put apple pieces in a juicer jar and pour milk in it</step>
           <step>add some powered sugar</step>
           <step>add ice cubes</step>
           <step>blend it well</step>
           <step>serve it cold</step>
       </prep>
       <nutrition calories="30" fat="0.6" protein="2.5" fiber="6"></nutrition>
       <rating>7.5 out of 10</rating>
</drink>
</drinks>


